spring.application.name=orm-learn
# Logs
logging.level.org.springframework=INFO
logging.level.com.cognizant=DEBUG

logging.level.org.hibernate.SQL=TRACE
logging.level.org.hibernate.type.descriptor.sql=TRACE

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/ormlearn
spring.datasource.username=root
spring.datasource.password=150911
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Show SQL
spring.jpa.show-sql=true